config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :items
    resources :reviews,only:[:show,:destroy,:index]
    resources :users,only:[:edit,:update]
  end

  scope module: :public do
    root 'homes#top'
    post 'users/guest_sign_in' => 'users#guest_sign_in', as: 'guest_sign_in'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/diagnosis' => "users#diagnosis", as: "diagnosis"
    get 'users/result' => "users#result", as: "result"
    patch 'users/save' => "users#save", as: "save"
    get 'user/favorites' => "users#favorites", as: "favorites"
    get 'items/ranking' => "items#ranking", as: "ranking"
    get 'items/whitening/ranking' => "items#whitening_ranking", as: "whitening_ranking"
    get 'items/wrinkle/ranking' => "items#wrinkle_ranking", as: "wrinkle_ranking"
    get 'items/moisturizing/ranking' => "items#moisturizing_ranking", as: "moisturizing_ranking"
    get 'items/acne_cure/ranking' => "items#acne_cure_ranking", as: "acne_cure_ranking"
    get 'items/irritation/ranking' => "items#irritation_ranking", as: "irritation_ranking"
    get 'search' => 'items#search'
    get 'reviews' => 'reviews#index', as: "reviews"

    resources :items,only:[:index,:show] do
      resources :reviews,only:[:new,:create,:destroy]
      resource :favorites,only:[:create,:destroy]
    end
  end
  #devise_for :admins
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  # belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :genre_id, presence:true
  validates :brand, presence: true
  validates :price, presence: true
  validates :capacity, presence: true
  validates :introduction, presence: true
  # validates :release_date, presence: true

  scope :where_genre_active, -> { joins(:genre) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    (price * 1.1).floor.to_s(:delimited)
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def avg_wrinkle
    unless self.reviews.empty?
      reviews.average(:wrinkle).round(1)
    else
      "未評価"
    end
  end

  def avg_whitening
    unless self.reviews.empty?
      reviews.average(:whitening).round(1)
    else
      "未評価"
    end
  end

  def avg_moisturizing
    unless self.reviews.empty?
      reviews.average(:moisturizing).round(1)
    else
      "未評価"
    end
  end

  def avg_acne_cure
    unless self.reviews.empty?
      reviews.average(:acne_cure).round(1)
    else
      "未評価"
    end
  end

  def avg_no_irritation
    unless self.reviews.empty?
      reviews.average(:no_irritation).round(1)
    else
      "未評価"
    end
  end

  def avg_reviews
    unless self.reviews.empty?
      ((avg_whitening + avg_wrinkle + avg_moisturizing + avg_acne_cure + avg_no_irritation)/5).round(1)
    else
      "未評価"
    end
  end

  def review_sort_value
    if avg_reviews == "未評価"
      -1
    else
      avg_reviews
    end
  end

  def whitening_sort_value
    if avg_whitening == "未評価"
      -1
    else
      avg_whitening
    end
  end

  def wrinkle_sort_value
    if avg_wrinkle == "未評価"
      -1
    else
      avg_wrinkle
    end
  end

  def moisturizing_sort_value
    if avg_moisturizing == "未評価"
      -1
    else
      avg_moisturizing
    end
  end

  def acne_cure_sort_value
    if avg_acne_cure == "未評価"
      -1
    else
      avg_acne_cure
    end
  end

  def no_irritation_sort_value
    if avg_no_irritation == "未評価"
      -1
    else
      avg_no_irritation
    end
  end

  def self.search(keyword)
      where(["name like? OR brand like? OR introduction like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @genres = Genre.all
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:success] = '削除しました'
    redirect_to admin_items_path
  end

  private
    def item_params
      params.require(:item).permit(:brand, :name, :item, :image, :genre_id, :price, :capacity, :release_date, :introduction)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/destroy.html.erb
<h1>Admin::Items#destroy</h1>
<p>Find me in app/views/admin/items/destroy.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="all-view">
  <div class="title">
    <h1>商品情報編集</h1>
  </div>
  <div class="form">
    <%= form_with model: @item, url:admin_item_path(@item.id),local:true do |f| %>
      <div class="field">
        <%= f.label :"商品画像" %><br>
        <div class="item-image">
          <%= image_tag @item.get_image(100, 100) %>
        </div>
        <div id="new-image"></div>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="field">
        <%= f.label :"ブランド" %><br>
        <%= f.text_field :brand, autofocus: true, size: 50 %>
      </div>
      <div class="field">
        <%= f.label :"商品名" %><br>
        <%= f.text_field :name, size: 50 %>
      </div>
      <div class="field">
        <%= f.label :"カテゴリー" %><br>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, selected: @item.genre_id), id:"inputGenre_id" %>
      </div>
      <div class="field">
        <%= f.label :"税抜価格" %></br>
        <%= f.text_field :price %>円
      </div>
      <div class="field">
        <%= f.label :"容量" %></br>
        <%= f.text_field :capacity %>
      </div>
      <div class="field">
        <%= f.label :"発売日" %></br>
        <%= raw sprintf(f.date_select(:release_date, include_blank: true, use_month_numbers: true, start_year: 2000, end_year: (Time.now.year + 1), date_separator: '%s'), '年 ', '月 ') + '日' %>
      </div>
      <div class="field">
        <%= f.label :"商品説明" %></br>
        <%= f.text_area :introduction, class: "introduction" %>
      </div>
      <div class="actions">
        <%= f.submit '変更を保存', class: "btn btn-dark btn-sm m-1" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="item-index">
  <div class="title">
    <h2>商品一覧</h2>
  </div>
  <div class="button">
    <%= link_to "商品追加", new_admin_item_path, class: "btn btn-dark btn-sm mb-5" %>
  </div>
  <table class="table">
    <tr class="record">
      <th class="t-id">商品ID</th>
      <th class="t-brand">ブランド</th>
      <th class="t-name">商品名</th>
      <th class="t-genre">カテゴリー</th>
      <th class="t-release">発売日</th>
      <th class="t-create">登録日時</th>
      <th class="t-edit"></th>
    </tr>
    <% @items.each do |item| %>
    <tr class="record">
      <td><%= item.id %></td>
      <td><%= item.brand %></td>
      <td><%= item.name %></td>
      <td><%= item.genre.name %></td>
      <td>
        <% if item.release_date.presence %>
          <%= item.release_date.strftime('%Y/%m/%d') %>
        <% else %>
          －
        <% end %>
      </td>
      <td><%= item.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
      <td><%= link_to "詳細", admin_item_path(item.id), class:"btn btn-dark btn-sm m-1" %></td>
    </tr>
    <% end %>
  </table>
  <%= paginate  @items %>
</div>

app/views/admin/items/new.html.erb
<div class="all-view">
  <div class="title">
    <h2>商品追加</h2>
  </div>
  <div class="form">
    <%= form_with model: @item, url:admin_items_path, local:true do |f| %>
      <div class="field">
        <%= f.label :"商品画像" %><br>
        <div id="new-image" ></div>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="field">
        <%= f.label :"ブランド" %><br>
        <%= f.text_field :brand, autofocus: true, size: 50 %>
      </div>
      <div class="field">
        <%= f.label :"商品名" %><br>
        <%= f.text_field :name, size: 50 %>
      </div>
      <div class="field">
        <%= f.label :"カテゴリー" %><br>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, selected: @item.genre_id), id:"inputGenre_id" %>
      </div>
      <div class="field">
        <%= f.label :"税抜価格" %></br>
        <%= f.text_field :price %>円
      </div>
      <div class="field">
        <%= f.label :"容量" %></br>
        <%= f.text_field :capacity %>
      </div>
      <div class="field">
        <%= f.label :"販売日" %></br>
        <%= raw sprintf(f.date_select(:release_date, use_month_numbers: true, start_year: 2000, end_year: (Time.now.year + 1), date_separator: '%s'), '年 ', '月 ') + '日' %>
      </div>
      <div class="field">
        <%= f.label :"商品説明" %></br>
        <%= f.text_area :introduction, class: "introduction" %>
      </div>
      <div class="actios">
        <%= f.submit '追加する', class: "btn btn-dark btn-sm m-1" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="all-view">
  <div class="title">
    <h2><span class="show-brand"><%= @item.brand %></span>　<%= @item.name %></h2>
  </div>
  <div class="item-show">
    <div class="item-image">
      <%= image_tag @item.get_image(300, 300) %>
    </div>
    <div class="item-introduction">
      <div class="item-info">
        <p>カテゴリー：<%= @item.genre.name %></p>
        <p>税込価格(税抜価格)：<%= @item.add_tax_price %>円(<%= @item.price.to_s(:delimited) %>円)／<%= @item.capacity %></p>
        <p>
          発売日：
          <% if @item.release_date.presence %>
            <%= @item.release_date.strftime('%Y/%m/%d') %>
          <% else %>
            －
          <% end %>
        </p>
        <p class="mb-0">商品説明</p>
        <p><%= @item.introduction %></p>
      </div>
      <div>
        <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-dark btn-sm m-1" %>
        <%= link_to "削除する", admin_item_path(@item.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-dark btn-sm m-1" %>
      </div>
    </div>
  </div>
</div>