config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :items
    resources :reviews,only:[:show,:destroy,:index]
    resources :users,only:[:edit,:update]
  end

  scope module: :public do
    root 'homes#top'
    post 'users/guest_sign_in' => 'users#guest_sign_in', as: 'guest_sign_in'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/diagnosis' => "users#diagnosis", as: "diagnosis"
    get 'users/result' => "users#result", as: "result"
    patch 'users/save' => "users#save", as: "save"
    get 'user/favorites' => "users#favorites", as: "favorites"
    get 'items/ranking' => "items#ranking", as: "ranking"
    get 'items/whitening/ranking' => "items#whitening_ranking", as: "whitening_ranking"
    get 'items/wrinkle/ranking' => "items#wrinkle_ranking", as: "wrinkle_ranking"
    get 'items/moisturizing/ranking' => "items#moisturizing_ranking", as: "moisturizing_ranking"
    get 'items/acne_cure/ranking' => "items#acne_cure_ranking", as: "acne_cure_ranking"
    get 'items/irritation/ranking' => "items#irritation_ranking", as: "irritation_ranking"
    get 'search' => 'items#search'
    get 'reviews' => 'reviews#index', as: "reviews"

    resources :items,only:[:index,:show] do
      resources :reviews,only:[:new,:create,:destroy]
      resource :favorites,only:[:create,:destroy]
    end
  end
  #devise_for :admins
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews = Review.all.order(id: "DESC")
    @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="all-view">
  <div class="title">
    <h2>口コミ一覧</h2>
  </div>
  <table class="table">
    <% @reviews.each do |review| %>
      <tr>
        <td>
        　<%= review.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
        </td>
        <td>
          <%= review.item.brand %>
        </td>
        <td>
          <%= link_to review.item.name, admin_item_path(review.item_id) %>
        </td>
        <td>
          <%= link_to review.user.name, edit_admin_user_path(review.user_id) %>
        </td>
        <td>
          <%= link_to "詳細", admin_review_path(review.id), class: "btn btn-dark btn-sm" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate  @reviews %>
</div>

app/views/admin/reviews/show.html.erb
<div class="all-view">
  <div class="title">
    <h2>口コミ詳細</h2>
  </div>
  <table class="t-review">
    <tr>
      <th>ブランド</th>
      <td><%= @review.item.brand %></td>
    </tr>
    <tr>
      <th>商品名</th>
      <td><%= link_to @review.item.name, admin_item_path(@review.item_id) %></td>
    </tr>
    <tr>
      <th>ユーザーID</th>
      <td><%= @review.user.id %></td>
    </tr>
    <tr>
      <th>ユーザーネーム</th>
      <td><%= link_to @review.user.name,  edit_admin_user_path(@review.user_id) %></td>
    </tr>
    <tr>
      <th>年齢</th>
      <td><%= @review.user.age_i18n %></td>
    </tr><tr>
      <th>性別</th>
      <td><%= @review.user.sex_i18n %></td>
    </tr>
    <tr>
      <th>投稿日時</th>
      <td><%= @review.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
    </tr>
    <tr>
      <th>保湿評価</th>
      <td><%= @review.moisturizing %></td>
    </tr>
    <tr>
      <th>美白評価</th>
      <td><%= @review.whitening %></td>
    </tr>
    <tr>
      <th>シワ評価</th>
      <td><%= @review.wrinkle %></td>
    </tr>
    <tr>
      <th>肌荒れ評価</th>
      <td><%= @review.acne_cure %></td>
    </tr>
    <tr>
      <th>安全性評価</th>
      <td><%= @review.no_irritation %></td>
    </tr>
    <tr>
      <th>コメント</th>
      <td><%= @review.comment %></td>
    </tr>
  </table>
  <div class="button">
    <%= link_to "削除", admin_review_path(@review.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-dark btn-sm" %>
  </div>
</div>