config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :items
    resources :reviews,only:[:show,:destroy,:index]
    resources :users,only:[:edit,:update]
  end

  scope module: :public do
    root 'homes#top'
    post 'users/guest_sign_in' => 'users#guest_sign_in', as: 'guest_sign_in'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/diagnosis' => "users#diagnosis", as: "diagnosis"
    get 'users/result' => "users#result", as: "result"
    patch 'users/save' => "users#save", as: "save"
    get 'user/favorites' => "users#favorites", as: "favorites"
    get 'items/ranking' => "items#ranking", as: "ranking"
    get 'items/whitening/ranking' => "items#whitening_ranking", as: "whitening_ranking"
    get 'items/wrinkle/ranking' => "items#wrinkle_ranking", as: "wrinkle_ranking"
    get 'items/moisturizing/ranking' => "items#moisturizing_ranking", as: "moisturizing_ranking"
    get 'items/acne_cure/ranking' => "items#acne_cure_ranking", as: "acne_cure_ranking"
    get 'items/irritation/ranking' => "items#irritation_ranking", as: "irritation_ranking"
    get 'search' => 'items#search'
    get 'reviews' => 'reviews#index', as: "reviews"

    resources :items,only:[:index,:show] do
      resources :reviews,only:[:new,:create,:destroy]
      resource :favorites,only:[:create,:destroy]
    end
  end
  #devise_for :admins
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :user,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cosmen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/75497fcafa.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm bg-dark text-white pt-1 pb-1">
      <nav>
        <a class="navbar-brand ml-5 mt-3" href="/"><%= image_tag 'COSMEN.png', size: '110x110' %></a>
          <div class="float-right mt-4 mr-5">
            <ul>
              <% if admin_signed_in? %>
                <li class="btn-flat-border"><%= link_to '会員一覧', admin_top_path, class: "btn" %></li>
                <li class="btn-flat-border"><%= link_to '商品一覧', admin_items_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to '口コミ一覧', admin_reviews_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn" %></li>
                <% elsif user_signed_in? %>
                  <p>ようこそ、<%= current_user.name %>さん!</p>
                  <li class="btn-flat-border"><%= link_to 'マイページ', mypage_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to '商品検索', items_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to 'ランキング', ranking_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to '化粧品診断', diagnosis_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %></li>
                <% else %>
                  <li class="btn-flat-border"><%= link_to '商品検索', items_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to '新規登録', new_user_registration_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to 'ログイン', new_user_session_path, class: "btn" %></li>
                  <li class="btn-flat-border"><%= link_to 'ゲストログイン', guest_sign_in_path, method: :post, class: "btn"  %></li>
                <% end %>
              </ul>
            </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <h6 class="mt-2 mb-3 text-center">Copyright © cosmen Co.,Ltd. All Rights Reserved.</h6>
    </footer>
  </body>
</html>